### ISSUE TITLE
ドキュメントのパッケージ読み込みの説明部分が不正確ではないか？

### ISSUE THREAD

**Issue by puripuri2100** [monaqa/satysfi-enumitem#3]
ドキュメントでは`@require: enumitem`で読み込むことができるとされていますが、これについては「satyrographosを用いずに手動でdist直下に`enumitem.satyh`を配置した場合」であることを明記しなければならないように感じました。

なぜならば、今や多くのユーザーはsatyrographosを使ってインストールしており、また、READMEでもsatyrographosを使ってインストールするように誘導しているからです。この場合、パッケージの読み込みは`@require: enumitem/enumitem`となります。READMEや現状との整合性を取るために、表記を変更し、「satyrographosを使ってインストールした場合」という条件を明記するのはどうでしょうか？

https://github.com/monaqa/satysfi-enumitem/blob/master/doc/enumitem.saty#L195

**Comment by monaqa** [comment]
ご指摘ありがとうございます。仰るとおり、ドキュメントの内容が古い（Satyrographos の導入前に書かれた）ようです。

現在は Satyrographos を用いたインストールを主に想定しているため、該当箇所を書き直して対応します。
